### ISSUE TITLE
Time wrong by 1H

### ISSUE THREAD

**Issue by jaket91-1** [gurgleapps/Gurgle-Apps-Word-Clock#1]
Hi guys, my clock arrived today and it's awesome, thanks so much for inventing it.

I seem to be running into a bug where the time being displayed by the clock is behind by 1H, possibly as a result of not conforming to DST? I haven't had chance to properly run through the code but if I do I will certainly poke around to assist. 

The web UI displays both the time as shown on the clock as well as the current local/system time (BST in the UK, UTC+1  at the time of writing) which is a little confusing but may be a clue, per the pic.

Keep up the awesome work!

<img width="535" alt="Screenshot 2024-04-09 at 17 09 35" src="https://github.com/gurgleapps/Gurgle-Apps-Word-Clock/assets/67487132/29fd84a8-e8d9-4384-a687-bf644c9ba79a">

**Comment by gurgleapps** [comment]
Hi,

Thanks so much for supporting us and buying the clock, we are very grateful. 
Thanks also for taknig the time to comment we are thrilled you like it.

The web UI shows the time returned by the word clock and the Time in the form field shows the current time.
The idea is that you most probably want to set the clock to the current time so the form is filled out for you.

When you press 'Update Time' it should set the word clock.

I'm wondering what happens when you set the minute say 10 minutes too fast. Is the minute correct and the hour still wrong?

Also what happens if you set it an hour ahead?

You can see what is returned from the clock if you check the javascript console as it logs all the settings from the clock when you update the time.

You can also peek at the payload it sends if you check the network tab in dev tools in the browser.

We are BST which is an hour ahead of UTC and it's working for us, we are trying to replicate the issue.

Thanks.
GurgleApps.

**Comment by andypiper** [comment]
This happened for me as well - initially it was 1H behind. After I clicked set in the web UI, it started showing the correct BST time.

**Comment by jaket91-1** [comment]
After looking at the code and the docs for the Micropython `ntptime` library, the manual syncing of the time through the UI is a required step as long as your local time is not the same as UTC. Doing this calculates the difference between UTC and the time set manually and saves this delta to the config file as `TIME_OFFSET` to persist across reboots. ntptime does not support passing a locale to figure out the current delta from UTC in your region so I think for now, this is the best option and we'll just have to remember to reset our clocks every March/October :)
